# Generated by Django 2.2.8 on 2019-12-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_tech', '0002_auto_20191210_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comment',
            field=models.IntegerField(default=0),
        ),
    ]
