# Generated by Django 3.0 on 2019-12-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0002_auto_20191209_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengunjung',
            name='hari_berkunjung',
            field=models.DateField(verbose_name='Hari Berkunjung'),
        ),
        migrations.AlterField(
            model_name='penjaga',
            name='jadwal_jaga',
            field=models.DateTimeField(verbose_name='Jadwal Jaga'),
        ),
    ]
