# Generated by Django 3.0 on 2019-12-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_tech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(default='', max_length=200)),
                ('title', models.CharField(default='', max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('content', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='mentee',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='profile_pic',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='quotes',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='experience',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='profile_pic',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='quotes',
            field=models.CharField(default='', max_length=200),
        ),
    ]
