# Generated by Django 3.0 on 2019-12-09 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=50)),
                ('nomor_telepon', models.CharField(max_length=15)),
                ('bidang', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelajaran', models.CharField(max_length=50)),
                ('jadwal_dimulai', models.DateTimeField(verbose_name='jadwal_dimulai')),
                ('jadwal_berakhir', models.DateTimeField(verbose_name='jadwal_berakhir')),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=50)),
                ('nomor_telepon', models.CharField(max_length=15)),
                ('nomor_absen', models.IntegerField(default=1)),
                ('nilai_rerata', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=50)),
                ('nomor_telepon', models.CharField(max_length=15)),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ata.MataPelajaran')),
            ],
        ),
        migrations.CreateModel(
            name='LiveCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_live_code', models.CharField(max_length=50)),
                ('banyak_soal', models.IntegerField(default=1)),
                ('bobot_nilai', models.IntegerField(default=100)),
                ('tanggal_pelaksanaan', models.DateTimeField(verbose_name='jadwal_berakhir')),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ata.MataPelajaran')),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_challenge', models.CharField(max_length=50)),
                ('banyak_soal', models.IntegerField(default=1)),
                ('bobot_nilai', models.IntegerField(default=100)),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ata.MataPelajaran')),
            ],
        ),
    ]
